version: '3'
services:
  api:
    build: 
      context: ./api/
    container_name: api
    working_dir: /www
    ports:
      - "3001:3001"
    volumes: 
      - ./api/:/www
    command: yarn start
  client:
    build:
      context: ./client/
    container_name: client
    working_dir: /www
    ports:
      - '3000:3000'
    volumes:
      - ./client/:/www
    command: yarn start