version: '3'
services:
  web:
    build: .
    working_dir: /www
    ports:
      - "3000:3000"
    volumes: 
      - .:/www
    command: node server.js
  rethinkdb:
    image: "rethinkdb"
    container_name: "rethinkdb"
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"