version: '3.8'
services:
  web:
    build: .
    working_dir: /www
    ports:
      - "3001:3001"
    volumes: 
      - .:/www
    command: nodemon server.js
  rethinkdb:
    image: "rethinkdb"
    container_name: "rethinkdb"
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"